# Site settings
title: Aravind M Nair
description: Techie | Gadget Freak | 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aravind M Nair
user_description: Software Developer, Gadget Lover, Passionate Blogger & Android Enthusiast
user_title: React Native Developer
email: aravind.nair2010@gmail.com
twitter_username: https://twitter.com/aravindnair
github_username:  https://github.com/aravi365
code_body: I build efficient native mobile applications for both iOS and android using React Native - a javascript framework that bring your ideas to life. 
tools_body: Using Github,Gitlab and Bitbucket version control systems and i love Visual Studio Code. Android Studio and XCode are my good friends!

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
